# Generated by Django 2.2 on 2019-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devamsizlik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devamsizlik',
            name='devamsizlik_tarihi',
            field=models.DateTimeField(default='2019-05-04 16:40', verbose_name='Tarih'),
        ),
    ]
