# Generated by Django 2.2 on 2019-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devamsizlik', '0003_auto_20190504_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='devamsizlik',
            name='saat',
            field=models.CharField(default='22:00', max_length=5, verbose_name='Saat'),
        ),
    ]
