# Generated by Django 2.2 on 2019-07-01 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devamsizlik', '0005_auto_20190608_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devamsizlik',
            name='devamsizlik_tarihi',
            field=models.DateField(verbose_name=datetime.datetime(2019, 7, 1, 16, 44, 49, 761547)),
        ),
        migrations.AlterField(
            model_name='devamsizlik',
            name='saat',
            field=models.CharField(default='16:00', max_length=5, verbose_name='Saat'),
        ),
    ]
