# Generated by Django 2.2 on 2019-07-01 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devamsizlik', '0006_auto_20190701_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devamsizlik',
            name='devamsizlik_tarihi',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 16, 45, 37, 139150)),
        ),
    ]
