# Generated by Django 2.2 on 2019-04-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci_dersleri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci_dersleri',
            name='ogrenci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci', to='ogrenci.Ogrenci', verbose_name='Öğrenci'),
        ),
    ]
