# Generated by Django 2.2 on 2019-05-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0003_auto_20190423_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='adres',
            field=models.CharField(max_length=200, null=True, verbose_name='Adres'),
        ),
    ]
