# Generated by Django 2.2 on 2019-04-08 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogrenci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('Id_ders', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ders_adi', models.CharField(max_length=25, verbose_name='Ders')),
                ('ders_yili', models.DateField(auto_now_add=True, verbose_name='Ders Yılı')),
                ('ogretmen', models.ForeignKey(limit_choices_to={'groups__name': 'ogretmenler'}, on_delete=django.db.models.deletion.CASCADE, related_name='ders', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen')),
            ],
        ),
        migrations.CreateModel(
            name='DersOgrenci',
            fields=[
                ('Id_dersogrenci', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersogrenci', to='dersler.Dersler', verbose_name='Ders')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrencis', to='ogrenci.Ogrenci', verbose_name='Öğrenci')),
            ],
        ),
    ]
