# Generated by Django 2.2 on 2019-04-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DersOgrenci',
        ),
    ]
