# Generated by Django 2.2 on 2019-04-22 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0002_delete_dersogrenci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersler',
            name='ogretmen',
            field=models.ForeignKey(limit_choices_to={'ogretmen_mi': 'True'}, on_delete=django.db.models.deletion.CASCADE, related_name='ders', to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen'),
        ),
    ]
