# Generated by Django 2.2 on 2019-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0004_auto_20190504_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersler',
            name='ders_yili',
            field=models.CharField(default='2019', max_length=4, verbose_name='Ders Yılı'),
        ),
    ]
